<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net48</TargetFramework><OutputType>Exe</OutputType><PlatformTarget>x86</PlatformTarget><UseWindowsForms>true</UseWindowsForms><LangVersion>latest</LangVersion><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><OfficePiaDirectory Condition="'$(OfficePiaDirectory)' == ''">$(WINDIR)\assembly\GAC_MSIL</OfficePiaDirectory></PropertyGroup>
 <ItemGroup><ProjectReference Include="../../src/Locus.Word/Locus.Word.csproj"/><Reference Include="System.Web.Extensions"/><Reference Include="System.Xml.Linq"/><Reference Include="Microsoft.CSharp"/><Reference Include="Microsoft.Office.Interop.Word"><HintPath>$(OfficePiaDirectory)\Microsoft.Office.Interop.Word\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Word.dll</HintPath><EmbedInteropTypes>true</EmbedInteropTypes></Reference></ItemGroup>
 <ItemGroup><Reference Include="office"><HintPath>$(OfficePiaDirectory)\office\15.0.0.0__71e9bce111e9429c\office.dll</HintPath><EmbedInteropTypes>true</EmbedInteropTypes></Reference></ItemGroup>
</Project>
