using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Locus.Application;
using Locus.Core;
using Locus.Core.Detection;
using Locus.Core.Export;

if(args.FirstOrDefault()=="--content-only")return await ContentVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/ux1/verification"));
if(args.FirstOrDefault()=="--ct4-only")return await Ct4Verification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/design-system/ct4/verification"));
if(args.FirstOrDefault()=="--balance-only")return await BalanceVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/bal1/verification"));
if(args.FirstOrDefault()=="--studio-balance-only")return await StudioBalanceVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/ui-design/balance-command"));
if(args.FirstOrDefault()=="--document-export-only")return await DocumentExportVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/doc1/verification"));
if(args.FirstOrDefault()=="--plot-only")return PlotVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/phase-g/verification"));
if(args.FirstOrDefault()=="--geometry-only")return GeometryVerification.Run(Path.GetFullPath(args.ElementAtOrDefault(1)??"artifacts/phase-g/verification"));

var output=Path.GetFullPath(args.FirstOrDefault()??"artifacts/sh");Directory.CreateDirectory(output);
var results=new List<object>();int failures=0;
async Task Check(string name,Func<Task> action){try{await action();results.Add(new{name,passed=true});}catch(Exception e){failures++;results.Add(new{name,passed=false,error=e.ToString()});Console.Error.WriteLine($"FAIL {name}: {e.Message}");}}
void Assert(bool value,string reason="Contract failed"){if(!value)throw new Exception(reason);}
Task Sync(Action action){action();return Task.CompletedTask;}
FormulaDocument Formula(string raw="x+1/2",FormulaSettings? settings=null,long revision=7){var result=AnalysisWire.Analyze(new(raw,revision,settings??new()));return new(Guid.Parse("0d064a7e-d035-4c12-a9e0-72ab11cf2579"),3,new(raw,revision,settings??new(),result,0,result.Regions.FirstOrDefault()?.Candidates.FirstOrDefault()?.Id),new());}
string Edit(string json,Action<JsonObject> edit,bool payload=false){var node=JsonNode.Parse(json)!.AsObject();if(payload){var inner=JsonNode.Parse(node["payload"]!.GetValue<string>())!.AsObject();edit(inner);node["payload"]=inner.ToJsonString();node["sha256"]=Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(node["payload"]!.GetValue<string>())));}else edit(node);return node.ToJsonString();}
var scheduler=new NativeAnalysisScheduler();
await Check("core-baseline-and-passive-date-contracts",async()=>{var report=await CoreVerification.RunInMemory(File.ReadAllText("corpus/m0/cases.json"));await File.WriteAllTextAsync(Path.Combine(output,"core-contracts.json"),report);using var data=JsonDocument.Parse(report);Assert(data.RootElement.GetProperty("summary").GetProperty("checks").GetInt32()==240&&data.RootElement.GetProperty("summary").GetProperty("failed").GetInt32()==0);});
await Check("source-selection-history-and-export-lease",async()=>{using var s=new FormulaSession(scheduler);s.UpdateSource("x+1/2");Assert(await s.AnalyzeAsync());var direct=s.State.CandidateId;Assert(s.State.Region!.Candidates.Count>1);var lease=s.Lease();var second=s.State.Region.Candidates[1];Assert(s.Select(0,second.Id));Assert(!s.IsCurrent(lease));Assert(s.State.Candidate!.Kind=="repair");Assert(s.Undo()&&s.State.CandidateId==direct);Assert(s.Redo()&&s.State.CandidateId==second.Id);var state=s.State;s.UpdateSource("can2");Assert(!s.CanExport);Assert(s.Undo()&&ReferenceEquals(state.Analysis,s.State.Analysis));Assert(s.State.CandidateId==second.Id);});
await Check("superseded-success-cannot-replace-new-result",async()=>{var delayed=new Deferred();using var s=new FormulaSession(delayed);s.UpdateSource("x^2");var old=s.AnalyzeAsync();s.UpdateSource("1/2");var current=s.AnalyzeAsync();Assert(delayed.Calls[0].Token.IsCancellationRequested);delayed.Complete(1);Assert(await current);var expected=s.State;delayed.Complete(0);Assert(!await old);Assert(s.State==expected&&s.CanExport&&!s.IsBusy);});
await Check("stale-error-cannot-clear-current-busy",async()=>{var d=new Deferred();using var s=new FormulaSession(d);s.UpdateSource("x^2");var old=s.AnalyzeAsync();s.UpdateSource("1/2");var current=s.AnalyzeAsync();d.Calls[0].Completion.SetException(new IOException("late"));await old;Assert(s.IsBusy&&s.Error=="");d.Complete(1);await current;Assert(s.CanExport);});
await Check("composition-cancels-work-and-is-one-undo",async()=>{var d=new Deferred();using var s=new FormulaSession(d);s.UpdateSource("x^2");var task=s.AnalyzeAsync();d.Complete(0);await task;var before=s.State;s.UpdateSource("x^2",true);s.UpdateSource("x m",true);s.UpdateSource("x mũ 2",true);Assert(!s.CanUndo&&!s.CanExport&&!await s.AnalyzeAsync()&&d.Calls.Count==1);s.UpdateSource("x mũ 2",false);Assert(s.Undo()&&s.State==before);Assert(s.Redo()&&s.State.Raw=="x mũ 2");});
await Check("composition-rejects-late-result",async()=>{var d=new Deferred();using var s=new FormulaSession(d);s.UpdateSource("x^2");var old=s.AnalyzeAsync();s.UpdateSource("x m",true);d.Complete(0);Assert(!await old&&s.State.Analysis==null&&s.IsComposing);});
await Check("settings-change-invalidates-result-and-undo-restores",async()=>{using var s=new FormulaSession(scheduler);s.UpdateSource("lc[x^2]");s.Configure(new(InputMode.Markers));await s.AnalyzeAsync();var previous=s.State;var lease=s.Lease();s.Configure(new(InputMode.Markers,"toan[[","]]"));Assert(!s.IsCurrent(lease));Assert(s.Undo()&&s.State==previous);});
await Check("source-limit-before-scheduler-and-raw-retained",async()=>{var d=new Deferred();using var s=new FormulaSession(d);var raw=new string('x',5000);s.UpdateSource(raw);Assert(!await s.AnalyzeAsync()&&d.Calls.Count==0&&s.State.Raw==raw&&s.Error.Contains("4.096"));});
await Check("timeout-is-recoverable-with-source-intact",async()=>{var d=new Deferred();using var s=new FormulaSession(d);s.UpdateSource("x^2");var first=s.AnalyzeAsync();d.Calls[0].Completion.SetException(new TimeoutException());Assert(!await first&&s.Error.Contains("thời gian")&&!s.CanExport&&s.State.Raw=="x^2");var retry=s.AnalyzeAsync();d.Complete(1);Assert(await retry&&s.CanExport&&s.Error=="");});
await Check("wrong-source-worker-result-is-rejected",async()=>{var d=new Deferred();using var s=new FormulaSession(d);s.UpdateSource("x^2");var task=s.AnalyzeAsync();d.Calls[0].Completion.SetResult(AnalysisWire.Analyze(new("1/2",1,new())));Assert(!await task&&!s.CanExport&&s.State.Raw=="x^2");});
await Check("dispose-cancels-and-forbids-late-result",async()=>{var d=new Deferred();var s=new FormulaSession(d);s.UpdateSource("x^2");var task=s.AnalyzeAsync();s.Dispose();Assert(d.Calls[0].Token.IsCancellationRequested);d.Complete(0);Assert(!await task&&!s.CanExport);});
await Check("view-detach-keeps-session-selection-and-history",async()=>{using var model=new FormulaWorkspace(scheduler);await model.Session.AnalyzeAsync();var old=model.Session.State;var lease=model.Session.Lease();model.Session.DetachView();Assert(model.Session.State==old&&model.Session.CanUndo&&!model.Session.IsCurrent(lease));});
await Check("export-lease-cannot-cross-sessions",async()=>{using var a=new FormulaSession(scheduler);using var b=new FormulaSession(scheduler);a.UpdateSource("x^2");b.UpdateSource("x^2");await a.AnalyzeAsync();await b.AnalyzeAsync();Assert(a.State.CandidateId==b.State.CandidateId&&!b.IsCurrent(a.Lease()));});
await Check("bounded-history-and-redo-branch",()=>Sync(()=>{using var s=new FormulaSession(scheduler);for(int i=0;i<110;i++)s.UpdateSource($"x+{i}");int count=0;while(s.Undo())count++;Assert(count==FormulaSession.HistoryLimit);Assert(s.Redo());s.UpdateSource("1/2");Assert(!s.CanRedo);}));
var formula=Formula("👩‍🏫 e\u0301 Ta có lc[x mu\u0303 2] và lc[1 trên 2].",new(InputMode.Markers),9007199254740993);
var json=DocumentCodec.Serialize(formula);
await Check("preferences-roundtrip-and-invalid-version",()=>Sync(()=>{var value=new EditorPreferences(1,new(InputMode.Markers,"toan[[","]]"),new(64,3,true),false);Assert(EditorPreferences.Read(value.Serialize())==value);Assert(EditorPreferences.Read("{\"version\":99}")==null);Assert(EditorPreferences.Read("[]")==null);Assert(EditorPreferences.Read(value.Serialize().Replace("Markers","Missing"))==null);}));
await Check("unused-invalid-markers-do-not-block-explicit",async()=>{using var s=new FormulaSession(scheduler);s.Configure(new(InputMode.Explicit,"",""));s.UpdateSource("x^2");Assert(await s.AnalyzeAsync()&&s.CanExport);var doc=new FormulaDocument(Guid.NewGuid(),0,s.State,new());Assert(DocumentCodec.Open(DocumentCodec.Serialize(doc)).Document is FormulaDocument);});
await Check("imported-near-max-revision-remains-editable",()=>Sync(()=>{using var s=new FormulaSession(scheduler);s.Load(new("x^2",long.MaxValue-1,new()));s.UpdateSource("x^3");Assert(s.State.SourceRevision==0&&s.State.Raw=="x^3");}));
await Check("formula-roundtrip-nfd-emoji-spans-int64-selection",()=>Sync(()=>{var opened=(FormulaDocument)DocumentCodec.Open(json).Document!;Assert(opened.State.Raw==formula.State.Raw&&opened.State.SourceRevision==9007199254740993);Assert(DocumentCodec.Serialize(opened)==json);Assert(opened.State.Analysis!.Regions.Count==2);using var session=new FormulaSession(new Deferred());session.Load(opened.State);Assert(session.CanExport&&!session.CanUndo&&session.State.Analysis!.Source.Raw==formula.State.Raw);}));
await Check("repair-choice-persists-without-reparse",()=>Sync(()=>{var doc=Formula();doc=doc with {State=doc.State with {CandidateId=doc.State.Region!.Candidates[1].Id}};var restored=(FormulaDocument)DocumentCodec.Open(DocumentCodec.Serialize(doc)).Document!;Assert(restored.State.Candidate!.Kind=="repair"&&restored.State.CandidateId==doc.State.CandidateId);}));
await Check("invalid-raw-source-remains-saveable",()=>Sync(()=>{var doc=new FormulaDocument(Guid.NewGuid(),0,new(new string('x',5000),3,new()),new());Assert(DocumentCodec.Open(DocumentCodec.Serialize(doc)).Document is FormulaDocument saved&&saved.State.Raw.Length==5000&&saved.State.Analysis==null);}));
await Check("plot-and-geometry-roundtrip-independent-kinds",()=>Sync(()=>{WorkspaceDocument[] documents=[new PlotDocument(Guid.NewGuid(),2,[new("f","x^2")],new()),new GeometryDocument(Guid.NewGuid(),4,[new("A",0,1,"A"),new("B",2,0,"B")],[new("AB","A","B","dashed")])];foreach(var doc in documents){var encoded=DocumentCodec.Serialize(doc);Assert(DocumentCodec.Serialize(DocumentCodec.Open(encoded).Document!)==encoded);}}));
foreach(var (name,bad) in new[]{("future-version",Edit(json,n=>n["version"]=99)),("unknown-kind",Edit(json,n=>n["kind"]="future")),("checksum",Edit(json,n=>n["sha256"]="00")),("missing-source",Edit(json,n=>n.Remove("raw"),true)),("null-settings",Edit(json,n=>n["settings"]=null,true)),("unknown-candidate",Edit(json,n=>n["candidateId"]="wrong",true)),("source-snapshot-mismatch",Edit(json,n=>n["raw"]="x+1",true)),("source-revision-mismatch",Edit(json,n=>n["sourceRevision"]=8,true)),("duplicate-envelope",json.Insert(1,"\"version\":1,")),("unknown-fields",Edit(json,n=>n["newUnknownField"]=42)),("invalid-json","["), ("null-document","null")})
    await Check("retain-original/"+name,()=>Sync(()=>{var result=DocumentCodec.Open(bad);Assert(!result.IsSupported&&result.OriginalJson==bad);using var s=new FormulaSession(scheduler);s.Load(formula.State);var before=s.State;if(result.Document is FormulaDocument f)s.Load(f.State);Assert(s.State==before);}));
await Check("geometry-rejects-dangling-reference",()=>Sync(()=>{try{DocumentCodec.Serialize(new GeometryDocument(Guid.NewGuid(),1,[new("A",0,0,"A")],[new("line","A","missing")]));throw new Exception("Invalid graph accepted");}catch(FormatException){}}));
await Check("wire-preserves-exact-snapshots",()=>Sync(()=>{var wire=AnalysisWire.Serialize(formula.State.Analysis!);Assert(AnalysisWire.Serialize(AnalysisWire.Deserialize(wire))==wire);}));
var parity=new List<object>();using(var corpus=JsonDocument.Parse(File.ReadAllText("corpus/m0/cases.json")))
foreach(var item in corpus.RootElement.GetProperty("cases").EnumerateArray().Where(c=>c.GetProperty("status").GetString()!="pending"&&c.GetProperty("context").GetProperty("action").GetString()!="reopen_snapshot")){
 var c=item.GetProperty("context");var mode=c.GetProperty("inputMode").GetString() switch{"passive"=>InputMode.Passive,"marked"=>InputMode.Markers,_=>InputMode.Explicit};var settings=new FormulaSettings(mode,c.TryGetProperty("delimiters",out var d)?d.GetProperty("open").GetString()!:"lc[",c.TryGetProperty("delimiters",out d)?d.GetProperty("close").GetString()!:"]");var request=new AnalysisRequest(item.GetProperty("source").GetProperty("raw").GetString()!,7,settings);var wireRequest=AnalysisWire.Request(request);try{parity.Add(new{id=item.GetProperty("id").GetString(),request=wireRequest,result=AnalysisWire.Run(wireRequest),error=(string?)null});}catch(Exception){parity.Add(new{id=item.GetProperty("id").GetString(),request=wireRequest,result=(string?)null,error="rejected"});}}
await File.WriteAllTextAsync(Path.Combine(output,"worker-native-fixtures.json"),JsonSerializer.Serialize(parity));
await File.WriteAllTextAsync(Path.Combine(output,"native-roundtrip.locus"),json,new UTF8Encoding(false));
await File.WriteAllTextAsync(Path.Combine(output,"future.locus"),Edit(json,n=>n["version"]=99),new UTF8Encoding(false));
var report=new{status=failures==0?"PASSED":"FAILED",total=results.Count,failed=failures,results};await File.WriteAllTextAsync(Path.Combine(output,"application-tests.json"),JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine(JsonSerializer.Serialize(new{report.status,report.total,report.failed,workerFixtures=parity.Count}));return failures==0?0:1;

sealed class Deferred : IAnalysisScheduler
{
    public List<(AnalysisRequest Request,CancellationToken Token,TaskCompletionSource<AnalysisResult> Completion)> Calls {get;}=[];
    public Task<AnalysisResult> AnalyzeAsync(AnalysisRequest request,CancellationToken token){var completion=new TaskCompletionSource<AnalysisResult>();Calls.Add((request,token,completion));return completion.Task;}
    public void Complete(int index){var call=Calls[index];call.Completion.SetResult(AnalysisWire.Analyze(call.Request));}
}
