import {chromium,firefox} from '../sh/node_modules/playwright/index.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const kind=process.argv[2]??'chromium',out=`artifacts/web1/runs/${kind}`;await mkdir(out,{recursive:true});
const browser=await(kind==='firefox'?firefox:chromium).launch();
const context=await browser.newContext({viewport:{width:1280,height:960},acceptDownloads:true});
if(kind==='chromium')await context.grantPermissions(['clipboard-read','clipboard-write']);
const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const ready=()=>page.locator('.locus-app[data-ready=true]').waitFor({timeout:45000});
const rendered=()=>page.locator('#formula-preview[data-rendered=true] svg').waitFor({timeout:30000});
async function input(raw){await page.locator('#source').fill(raw);await page.waitForFunction(x=>document.querySelector('#source-count')?.textContent===`${x.length} ký tự`&&document.querySelector('.locus-app')?.dataset.busy==='false',raw);}
async function formula(raw){await input(raw);await rendered();}
async function latex(){await page.locator('.technical').evaluate(el=>el.open=true);return page.locator('#latex-output').textContent();}
async function saved(){await page.waitForFunction(()=>document.querySelector('#draft-status')?.textContent.includes('Đã lưu nháp'));await page.waitForTimeout(400);}
async function check(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);await page.screenshot({path:`${out}/web1-failure-${results.length}.png`,fullPage:true}).catch(()=>{});}}
async function download(selector,name){const pending=page.waitForEvent('download');await page.locator(selector).click();const d=await pending;await d.saveAs(`${out}/${name}`);return readFile(`${out}/${name}`);}
try{
await page.goto('http://127.0.0.1:4183/');await ready();await rendered();
await check('complete-offline-cache-before-editor',async()=>{assert.match(await page.locator('#offline-status').innerText(),/offline/);const data=await page.evaluate(async()=>({controller:!!navigator.serviceWorker.controller,keys:await caches.keys(),build:document.querySelector('meta[name=locus-build]').content}));assert(data.controller);assert(data.keys.includes('locus-app-'+data.build));});
await check('keyboard-focus-choice-and-history',async()=>{await formula('x+1/2');await page.locator('#copy-latex').focus();await page.keyboard.press('Alt+i');assert.equal(await page.evaluate(()=>document.activeElement.id),'source');await page.keyboard.press('Alt+2');await rendered();assert.equal(await latex(),'\\frac{x+1}{2}');await page.keyboard.press('Control+z');await rendered();assert.equal(await latex(),'x+\\frac{1}{2}');await page.keyboard.press('Control+y');await rendered();assert.equal(await latex(),'\\frac{x+1}{2}');});
await check('draft-reload-retains-repair-and-view',async()=>{await page.locator('#font-size').selectOption('64');await rendered();const id=await page.locator('#formula-preview').getAttribute('data-candidate');await saved();await page.reload();await ready();await rendered();assert.equal(await page.locator('#formula-preview').getAttribute('data-candidate'),id);assert.equal(await latex(),'\\frac{x+1}{2}');assert.equal(await page.locator('#font-size').inputValue(),'64');});
await check('synchronous-journal-recovers-before-debounce',async()=>{await page.locator('#source').evaluate(el=>{el.value='x mũ 3 + 7';el.dispatchEvent(new InputEvent('input',{bubbles:true}));location.reload();});await ready();await rendered();assert.equal(await page.locator('#source').inputValue(),'x mũ 3 + 7');assert.equal(await latex(),'{x}^{3}+7');});
await check('custom-markers-and-preferences-reload',async()=>{await page.locator('#mode').selectOption('Markers');await page.locator('#marker-open').fill('toan[[');await page.locator('#marker-open').blur();await page.locator('#marker-close').fill(']]');await page.locator('#marker-close').blur();await formula('Ví dụ toan[[1 trên 2]] nhé.');await saved();await page.reload();await ready();await rendered();assert.equal(await page.locator('#marker-open').inputValue(),'toan[[');assert.equal(await latex(),'\\frac{1}{2}');});
await check('duplicate-tab-does-not-overwrite-draft',async()=>{await saved();const firstId=await page.evaluate(()=>sessionStorage.getItem('locus.web1.tab'));const pending=context.waitForEvent('page');const second=await page.evaluateHandle(()=>window.open('/','_blank'));const other=await pending;await other.locator('.locus-app[data-ready=true]').waitFor({timeout:45000});const secondId=await other.evaluate(()=>sessionStorage.getItem('locus.web1.tab'));assert.notEqual(secondId,firstId);await other.locator('#source').fill('x+9');await other.waitForTimeout(1200);await page.reload();await ready();await rendered();assert.equal(await page.locator('#source').inputValue(),'Ví dụ toan[[1 trên 2]] nhé.');await other.close();await second.dispose();});
await check('clipboard-svg-and-text-formats',async()=>{await page.locator('#mode').selectOption('Explicit');await formula('x mũ 2');await page.locator('#copy-svg').click();await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('sao chép')||document.querySelector('#transfer-fallback'));if(kind==='chromium'){const items=await page.evaluate(async()=>{const list=await navigator.clipboard.read();return Promise.all(list.map(async x=>({types:x.types,text:await(await x.getType(x.types[0])).text()})));});assert(items.some(x=>x.text.includes('<svg')));}await page.locator('.technical').evaluate(el=>el.open=true);for(const format of ['latex','mathml','omml','source']){await page.locator('#copy-'+format).click();if(kind==='chromium'){const value=await page.evaluate(()=>navigator.clipboard.readText());assert(value.length>0);}}});
await check('clipboard-denied-download-fallback',async()=>{await page.evaluate(()=>{globalThis.originalClipboardWrite=navigator.clipboard.write;Object.defineProperty(navigator.clipboard,'write',{configurable:true,value:async()=>{throw new DOMException('Denied','NotAllowedError');}});});await page.locator('#copy-png').click();await page.locator('#transfer-fallback').waitFor();const bytes=await download('#transfer-fallback','fallback.png');assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.equal(await page.locator('#source').inputValue(),'x mũ 2');await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'write',{configurable:true,value:globalThis.originalClipboardWrite}));});
await check('save-picker-cancel-and-failure-retain-source',async()=>{if(kind==='firefox'){assert.equal(await page.locator('#save-as-document').count(),0);return;}await page.evaluate(()=>{globalThis.originalPicker=showSaveFilePicker;globalThis.showSaveFilePicker=async()=>{throw new DOMException('Cancelled','AbortError');};});await page.locator('#save-as-document').click();await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('Đã hủy'));assert.equal(await page.locator('#source').inputValue(),'x mũ 2');await page.evaluate(()=>{globalThis.showSaveFilePicker=async()=>({createWritable:async()=>{throw Error('Disk full');}});});await page.locator('#save-as-document').click();await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('Chưa chuyển'));assert.equal(await page.locator('#source').inputValue(),'x mũ 2');await page.evaluate(()=>globalThis.showSaveFilePicker=globalThis.originalPicker);});
await check('picker-source-change-cancels-stale-write',async()=>{if(kind==='firefox')return;await page.evaluate(()=>{globalThis.pickerWrites=0;globalThis.showSaveFilePicker=()=>new Promise(resolve=>globalThis.finishPicker=()=>resolve({createWritable:async()=>{globalThis.pickerWrites++;return {write:async()=>{},close:async()=>{}};}}));});await page.locator('#save-as-document').click();await input('x+5');await page.evaluate(()=>globalThis.finishPicker());await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('Đã hủy'));assert.equal(await page.evaluate(()=>globalThis.pickerWrites),0);await page.evaluate(()=>globalThis.showSaveFilePicker=globalThis.originalPicker);});
await check('offline-reload-worker-font-and-export',async()=>{await formula('căn((x+1)/2)');await saved();await context.setOffline(true);await page.reload();await ready();await rendered();assert.equal(await page.locator('#source').inputValue(),'căn((x+1)/2)');await formula('can2');assert.equal(await latex(),'\\sqrt{2}');const bytes=await download('#download-svg','offline.svg');assert(bytes.toString().includes('<path'));await context.setOffline(false);});
await check('local-draft-future-version-retained-original',async()=>{const future=await readFile('artifacts/web1/future.locus','utf8');await saved();await page.evaluate(async json=>{const open=indexedDB.open('locus-local-v1',1);const db=await new Promise((r,j)=>{open.onsuccess=()=>r(open.result);open.onerror=j;});await new Promise((r,j)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put({id:sessionStorage.getItem('locus.web1.tab'),document:json,raw:'future',time:Date.now()});tx.oncomplete=r;tx.onerror=j;});db.close();},future);await page.reload();await ready();await page.locator('#recover-file').waitFor();const bytes=await download('#recover-file','future-draft-original.locus');assert.equal(bytes.toString(),future);});
await check('autosave-off-does-not-claim-saved',async()=>{await page.locator('#auto-save').uncheck();await formula('x+88');await page.waitForFunction(()=>document.querySelector('#draft-status')?.textContent.includes('đang tắt'));await page.locator('#auto-save').check();await saved();});
await check('draft-write-failure-keeps-editor-usable',async()=>{await page.evaluate(()=>{globalThis.realTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){if(args[1]==='readwrite')throw new DOMException('Full','QuotaExceededError');return globalThis.realTransaction.apply(this,args);};});await formula('x+99');await page.waitForFunction(()=>document.querySelector('#draft-status')?.textContent.includes('Chưa lưu được nháp'));assert.equal(await latex(),'x+99');await page.evaluate(()=>IDBDatabase.prototype.transaction=globalThis.realTransaction);await formula('x+100');await saved();});
await check('mobile-width-and-context-export',async()=>{await page.setViewportSize({width:390,height:844});await rendered();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#formula-preview').click({button:'right'});await page.locator('.context-menu').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.context-menu').count(),0);await page.screenshot({path:`${out}/mobile.png`,fullPage:true});await page.setViewportSize({width:1280,height:960});await page.screenshot({path:`${out}/desktop.png`,fullPage:true});});
await check('no-unhandled-browser-errors',async()=>assert.deepEqual(errors,[]));
}finally{await writeFile(`${out}/web1.json`,JSON.stringify({status:results.every(r=>r.passed)?'PASSED':'FAILED',kind,version:browser.version(),results,errors},null,2));await browser.close();}
process.exitCode=results.some(r=>!r.passed)?1:0;
