import {readFile,writeFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const json=async path=>JSON.parse(await readFile(path,'utf8'));
const hash=async path=>createHash('sha256').update(await readFile(path)).digest('hex');
const build=await json('artifacts/sh/current-build.json'),packages=await json('artifacts/sh/package.json');assert.deepEqual(build,packages.build);
const paths=['application-tests.json','core-contracts.json','worker-chromium.json','worker-firefox.json','native-integration.json','renderer-comparison.json','clipboard-os.json','export-safety.json','package-validation.json','m2-regression/verification.json',...['chromium','firefox','desktop'].map(x=>`runs/${x}/ui.json`)];
const evidence=[];for(const relative of paths){const path='artifacts/sh/'+relative;const report=await json(path);if(report.status)assert(report.status.startsWith('PASS'),path);if(report.failed!==undefined)assert.equal(report.failed,0,path);if(report.results)assert(!report.results.some(r=>r.passed===false||r.status==='FAIL'),path);if(Array.isArray(report))assert(report.every(r=>r.status==='PASSED'),path);evidence.push({path,sha256:await hash(path)});}
const core=await json('artifacts/sh/core-contracts.json');assert.equal(core.summary.checks,238);assert.equal(core.summary.failed,0);
const runtime10=await hash('artifacts/sh/runtime-net10.txt');assert.equal(runtime10,await hash('artifacts/sh/runtime-net48-x86.txt'));
const previous=await json('artifacts/web/compatibility.json');const productionCore=previous.sources.filter(s=>s.path.startsWith('src/Locus.Core/'));
for(const file of productionCore)assert.equal(await hash(file.path),file.sha256,file.path);
const oldReleases=[['artifacts/releases/Locus-0.2.0-alpha-win-x64.zip','86d2de0af40dcaca573d00538a6493a38dbbbaec60a7aaaf941c1b008fffbe55'],['artifacts/releases/Locus-Word-0.3.0-alpha-x86.zip','f2a6c5868625c22df5826a9799b39d562f6ca84cdd8dee033f80f52f0fd2215c'],['artifacts/releases/Locus-Web-WEB0-static.zip','3536ce25393d9bf4599c825242217da04de09f99f419e3a1791f234508803908']];
// Historical releases are read-only inputs; this receipt never replaces them.
for(const [path,expected] of oldReleases)assert.equal(await hash(path),expected,path);
const sources=[];async function scan(directory){for(const item of await readdir(directory,{withFileTypes:true})){if(['bin','obj','vendor','node_modules'].includes(item.name))continue;const path=join(directory,item.name).replaceAll('\\','/');if(item.isDirectory())await scan(path);else sources.push({path,sha256:await hash(path)});}}
for(const directory of ['src/Locus.Application','src/Locus.Editor','src/Locus.Worker','src/Locus.Web','src/Locus.Desktop.Shared','tests/Locus.Application.Tests','tests/Locus.Shared.Desktop.Tests','tools/sh'])await scan(directory);
const ui={};for(const host of ['chromium','firefox','desktop']){const r=await json(`artifacts/sh/runs/${host}/ui.json`);assert.equal(r.results.length,14);assert(r.results.every(x=>x.passed));ui[host]={version:r.browserVersion,groups:r.results.length};}
const report={schemaVersion:'locus-sh-acceptance/1',capturedAtUtc:new Date().toISOString(),status:'PASSED_SHARED_EDITOR_FOUNDATION',milestone:'SH',tasks:Object.fromEntries(['SH-01','SH-02','SH-03','SH-04'].map(id=>[id,'DONE'])),progress:{completed:4,total:4,percent:100,scope:'SH only, not WEB1 or whole product'},build,ui,applicationGroups:32,coreContracts:238,workerParityPerBrowser:104,nativeIntegrationGroups:11,exportSafetyGroups:5,matchingRendererCases:7,baseline:{productionCoreFilesUnchanged:productionCore.length,runtimeProbeSources:13,runtimeOutputHash:runtime10,m2RegressionGroups:40,historicalReleases:oldReleases.map(([path,sha256])=>({path,sha256}))},packages:packages.packages,evidence,sources,limits:['Local preview; no public deployment or offline reload/PWA.','No automatic drafts on reload/app exit; save .locus first.','SH desktop entry point is separate from the M2 portable baseline.','Composition automation is not the real UniKey Telex/VNI release matrix; WEB1-03 remains open.','Formula only; Plot/Geometry schema foundations do not implement their editors.','W0 remains 4/6; G2/G3 and A/B decision unchanged.','Worker publish preserves reflection serializer assemblies; IL2026 warnings are recorded in build logs.'],next:'WEB1-01'};
await writeFile('artifacts/sh/acceptance.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,progress:report.progress,ui,coreFiles:productionCore.length,sourceFiles:sources.length}));
